version: '3'

# networks:
#     default: { external: { name: 'myapplication' }}

services:
  web:
    build: .
    restart: always
    env_file: .env
    ports:
        - '127.0.0.1:${SPCHI_PORT}:8888'

